/* Creates the table used by import_landmarks_to_sql.py when it is absent.
   This does not modify an existing dbo.hand_landmarks table. */
IF OBJECT_ID(N'dbo.hand_landmarks', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.hand_landmarks (
        id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        label CHAR(1) NOT NULL,
        x0 FLOAT NOT NULL, y0 FLOAT NOT NULL, z0 FLOAT NOT NULL,
        x1 FLOAT NOT NULL, y1 FLOAT NOT NULL, z1 FLOAT NOT NULL,
        x2 FLOAT NOT NULL, y2 FLOAT NOT NULL, z2 FLOAT NOT NULL,
        x3 FLOAT NOT NULL, y3 FLOAT NOT NULL, z3 FLOAT NOT NULL,
        x4 FLOAT NOT NULL, y4 FLOAT NOT NULL, z4 FLOAT NOT NULL,
        x5 FLOAT NOT NULL, y5 FLOAT NOT NULL, z5 FLOAT NOT NULL,
        x6 FLOAT NOT NULL, y6 FLOAT NOT NULL, z6 FLOAT NOT NULL,
        x7 FLOAT NOT NULL, y7 FLOAT NOT NULL, z7 FLOAT NOT NULL,
        x8 FLOAT NOT NULL, y8 FLOAT NOT NULL, z8 FLOAT NOT NULL,
        x9 FLOAT NOT NULL, y9 FLOAT NOT NULL, z9 FLOAT NOT NULL,
        x10 FLOAT NOT NULL, y10 FLOAT NOT NULL, z10 FLOAT NOT NULL,
        x11 FLOAT NOT NULL, y11 FLOAT NOT NULL, z11 FLOAT NOT NULL,
        x12 FLOAT NOT NULL, y12 FLOAT NOT NULL, z12 FLOAT NOT NULL,
        x13 FLOAT NOT NULL, y13 FLOAT NOT NULL, z13 FLOAT NOT NULL,
        x14 FLOAT NOT NULL, y14 FLOAT NOT NULL, z14 FLOAT NOT NULL,
        x15 FLOAT NOT NULL, y15 FLOAT NOT NULL, z15 FLOAT NOT NULL,
        x16 FLOAT NOT NULL, y16 FLOAT NOT NULL, z16 FLOAT NOT NULL,
        x17 FLOAT NOT NULL, y17 FLOAT NOT NULL, z17 FLOAT NOT NULL,
        x18 FLOAT NOT NULL, y18 FLOAT NOT NULL, z18 FLOAT NOT NULL,
        x19 FLOAT NOT NULL, y19 FLOAT NOT NULL, z19 FLOAT NOT NULL,
        x20 FLOAT NOT NULL, y20 FLOAT NOT NULL, z20 FLOAT NOT NULL,
        imported_at DATETIME2 NOT NULL CONSTRAINT DF_hand_landmarks_imported_at DEFAULT SYSUTCDATETIME()
    );
END
